

def HandleException(ErrorMessage,FunctionName):

    print("Error : " + ErrorMessage + " ; raised while executing the function  " + FunctionName)